#!/bin/bash

# Escape all the special characters in the filename
filename="\*\\\\'\"Best School\"\'\\\\*\$\\?\\*\*\*\*\*:)"

# Create the file with the specified name
echo "Best School" > "$filename"
