#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -of "4-to_infinity_and_beyond")

# Send a termination signal to the process
[ -n "$pid" ] && kill -TERM "$pid"
